name: CI

on:
  push:
    branches: [ main, tests ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ["1.25.x"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: Verify modules
        run: go mod tidy && git diff --exit-code || (echo "Run 'go mod tidy' locally" && exit 1)
      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=5m
      - name: Vet
        run: go vet ./...
      - name: Test (race, coverage)
        shell: bash
        run: go test -race -covermode=atomic -coverprofile=coverage.out ./...
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}
          path: coverage.out
      - name: Build
        run: go build -ldflags="-s -w" -o how .
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: how-${{ matrix.os }}
          path: how
